### ISSUE TITLE
False true-positive

### ISSUE THREAD

**Issue by mbhall88** [iqbal-lab-org/varifier#35] opened 2021-11-08 22:40 UTC
I was comparing hap.py and varifier and noticed differences in precision and recall.

For the interest of being concrete I zoomed in on one variant which hap.py and varifier make different calls for.

I used the varifier truth VCF as input to hap.py

The variant in the truth VCF

```
NC_000962.3     4359165 1937    G       GC      .       PASS    .       GT      1/1
```

Here is the variant from hap.py's VCF

```
NC_000962.3     4359165 .       G       GC      0       .       BS=4359163      GT:BD:BK:BI:BVT:BLT:QQ  1/1:FN:lm:i1_5:INDEL:homalt:.   ./.:.:.:.:NOCALL:nocall:0
NC_000962.3     4359165 .       G       C       232     .       BS=4359163      GT:BD:BK:BI:BVT:BLT:QQ  ./.:.:.:.:NOCALL:nocall:.       1/1:FP:lm:tv:SNP:homalt:232
```

and varifier's precision VCF

```
NC_000962.3     4359165 .       G       C,T     232     PASS    ABQ4=36.441;BCALL=C;BaseCounts=0,173,1,1;BaseCounts4=0,169,0,1;DM4=-0.276;DM4L=-1.665;DP=175;DP4=0,0,79,91;DPT4L=-10.408;DZ4=-0.196;DZ4L=-1.731;GC=71.29;MQ=60;MQ4=60;PCALL4=0.994;PCONS4=0.994;SBR=0 GT:DP:VFR_ED_RA:VFR_ED_TA:VFR_ALLELE_LEN:VFR_ALLELE_MATCH_COUNT:VFR_ALLELE_MATCH_FRAC:VFR_IN_MASK:VFR_RESULT    1/1:170:1:0:1:1:1.0:0:TP
```

and varifier's recall VCF

```
NC_000962.3     4359165 1937    G       GC      .       PASS    .       GT:VFR_ED_RA:VFR_ED_TR:VFR_ED_TA:VFR_ALLELE_LEN:VFR_ALLELE_MATCH_COUNT:VFR_ALLELE_MATCH_FRAC:VFR_IN_MASK:VFR_RESULT  1/1:1:0:0:2:2:1.0:0:TP
```

and the entry in the original (Illumina/COMPASS) VCF with surrounding context

```
NC_000962.3     4359163 .       G       .       273     PASS    ABQ4=36.316;BCALL=G;BaseCounts=1,0,173,0;BaseCounts4=1,0,170,0;DM4=-0.245;DM4L=-1.638;DP=174;DP4=80,90,0,1;DPT4L=-9.888;DZ4=-0.17;DZ4L=-1.706;GC=72.28;MQ=60;MQ4=60;PCALL4=0.994;PCONS4=0.994;SBR=0   GT:DP   0/0:171
NC_000962.3     4359164 .       G       .       273     PASS    ABQ4=36.572;BCALL=G;BaseCounts=0,0,174,0;BaseCounts4=0,0,166,0;DM4=-0.399;DM4L=-1.871;DP=174;DP4=78,88,0,0;DPT4L=-14.408;DZ4=-0.299;DZ4L=-1.917;GC=71.29;MQ=60;MQ4=60;PCALL4=1;PCONS4=1;SBR=0 GT:DP   0/0:166
NC_000962.3     4359165 .       G       C,T     232     PASS    ABQ4=36.441;BCALL=C;BaseCounts=0,173,1,1;BaseCounts4=0,169,0,1;DM4=-0.276;DM4L=-1.665;DP=175;DP4=0,0,79,91;DPT4L=-10.408;DZ4=-0.196;DZ4L=-1.731;GC=71.29;MQ=60;MQ4=60;PCALL4=0.994;PCONS4=0.994;SBR=0 GT:DP   1/1:170
NC_000962.3     4359166 .       G       .       273     PASS    ABQ4=36.579;BCALL=G;BaseCounts=0,0,176,0;BaseCounts4=0,0,171,0;DM4=-0.245;DM4L=-1.614;DP=176;DP4=80,91,0,0;DPT4L=-9.408;DZ4=-0.17;DZ4L=-1.684;GC=71.29;MQ=60;MQ4=60;PCALL4=1;PCONS4=1;SBR=0   GT:DP   0/0:171
NC_000962.3     4359167 .       T       .       273     PASS    ABQ4=36.244;BCALL=T;BaseCounts=0,0,1,174;BaseCounts4=0,0,0,164;DM4=-0.46;DM4L=-1.973;DP=175;DP4=81,83,0,0;DPT4L=-16.408;DZ4=-0.35;DZ4L=-2.01;GC=71.29;MQ=60;MQ4=60;PCALL4=1;PCONS4=1;SBR=0    GT:DP   0/0:164
```

So according to the VCF, the sequence is `GGGGT -> GGCGT` and according to the truth `GGGGT -> GGGCGT`. I guess varifier has struggled here because it uses alignment and this is a hard variant to align correctly.

**Comment by martinghunt** [comment] 2021-11-09 09:08
Can you share the input files with me please?

**Comment by mbhall88** [comment] 2021-11-09 23:58
> Can you share the input files with me please?

Sure. I'll just give you the command I used to run it with the full paths (on codon).

```
(bcftools view -O v /hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/illumina/gvcfs/mada_102.compass.vcf.gz \
  | varifier vcf_eval --force --filter_pass PASS,. --flank_length 100 \
    --ref_mask /hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/resources/compass-mask.bed \
    --truth_mask /hps/nobackup/iqbal/mbhall/tech_wars/analysis/assembly/results/mada_102/flye/pacbio/assessment/mada_102.flye.accuracy.pacbio.bed
    /hps/nobackup/iqbal/mbhall/tech_wars/analysis/assembly/results/mada_102/flye/pacbio/decontam.assembly.flye.pacbio.fasta \
    /hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/resources/h37rv.fa \
    - \
    /hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/truth_eval/compass/mada_102/varifier) 2> \
/hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/logs/stderr/evaluate_compass_with_truth_assembly/mada_102.log
```

I used this container

```
/hps/nobackup/iqbal/mbhall/tech_wars/analysis/baseline_variants/.snakemake/singularity/ab56949353e1d09a70c74c1fed8f2d87.simg
```

Which was pulled from `docker://quay.io/iqballab/varifier:c5b6237` (i.e., the latest commit on `master`)

**Comment by martinghunt** [comment] 2021-11-11 09:31
We've discussed this offline - summary here. The region is in a tandem repeat, where there are numerous ways that the truth and ref sequences can align. Varifier makes these two records in its truth VCF:
```
NC_000962.3     4359163 1936    G       GGCGTGATCGGGGTTCCCGGGGTGATCGGGGTTCCC    .       PASS    .       GT      1/1                                            
NC_000962.3     4359165 1937    G       GC      .       PASS    .       GT      1/1
```
which are correct. But there are lots of ways of representing this. Another way is to have the insertion elsewhere and a SNP at 4359165. Hence hap.py and varifier calling apparently conflicting calls as correct at 4359165. Both tools are correct - the problem is more than one way to align the sequences.

Closing this because it's not a bug so much as a feature of indels, nothing we can do about it in the code.

**Closed** 2021-11-11 09:31 UTC

**Comment by mbhall88** [comment] 2021-11-11 23:57
Well technically speaking varifier is still wrong here though? It says that the SNP is a TP. But in both truth VCF scenarios the variant is an INDEL. Therefore the SNP is a FP correct?

**Comment by iqbal-lab** [comment] 2021-11-12 05:07
The indel in the truth VCF and the SNP (or the other way round,  whichever it is) in the compass VCF are both true. . They both correctly report what is there, but dependent on different alignments. A VCF of the sample can either have variants a,b or c,d (or in fact other options). The truth vcf has a,b. Compass chooses c,d. Both are right. Hap.py looks at the vcfs and says they seem to be different,  and who can blame it. Varifier looks at c,d and says they are right
